[workspace]
resolver = "2"
members = [
    "mandate-policy",
    "smart-account",
    "ed25519-verifier",
]

[workspace.package]
authors = ["hackathon"]
edition = "2021"
license = "MIT"
version = "0.1.0"
publish = false

[workspace.dependencies]
soroban-sdk = { version = "26.1.0" }
stellar-accounts = { version = "0.7.2" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
